TEAMS = [
    "Alianza Petrolera",
    "América de Cali",
    "Atlético Bucaramanga",
    "Atlético F. C.",
    "Atlético Huila",
    "Atlético Nacional",
    "Barranquilla F. C.",
    # "Boca Juniors de Cali",
    "Bogotá F. C.",
    "Boyacá Chicó",
    "Cortuluá",
    "Cúcuta Deportivo",
    "Deportes Quindío",
    "Deportes Tolima",
    "Deportivo Cali",
    "Deportivo Pasto",
    "Deportivo Pereira",
    "Envigado F. C.",
    "Fortaleza F. C.",
    "Independiente Medellín",
    "Independiente Santa Fe",
    "Jaguares de Córdoba",
    "Junior de Barranquilla",
    "La Equidad",
    "Leones F. C.",
    "Llaneros F. C.",
    "Millonarios",
    "Once Caldas",
    "Orsomarso S. C.",
    "Patriotas Boyacá",
    "Real Cartagena",
    "Real Santander",
    "Tigres F. C.",
    "Unión Magdalena",
    "Valledupar F. C.",
    "Rionegro Águilas",
]
